const ACTIONTYPES = {
  SPINNER: {
    START_SPINNING: 'START_SPINNING',
    STOP_SPINNING: 'STOP_SPINNING'
  },
  EMPLOYEES: {
    SET_EMPLOYEES: 'SET_EMPLOYEES',
    SET_EMPLOYEE_FOCUS: 'SET_EMPLOYEE_FOCUS',
    CLEAR_EMPLOYEE_FOCUS: 'CLEAR_EMPLOYEE_FOCUS'
  }
};

export default ACTIONTYPES;
